### ISSUE TITLE
The lower the movement speed, the worse the performance

### ISSUE THREAD

**Issue by l291351760** [tharaj90/OTSM-MATLAB-code#1]
Hi,
I am very happy to find your code. But I don't understand why in your algorithm, the lower the movement speed, the worse the performance?
Hope to hear from you and wish you good health！
best,
kun

**Comment by tharaj90** [comment]
Hi,

It is not actually entirely related to the movement speed. The reason is the delay and Doppler resolution of the receiver. 

For low speed, some paths cannot be resolved along the Doppler domain. If you check the Doppler and delay taps of the channel coeffs in the MATLAB code, you will find that there will be multiple paths with very similar delay and Doppler shifts and therefore they almost seem like a single path and hence the diversity offered by the channel is reduced. The OTSM and the similar OTFS performance improves with more separable paths (either along the delay or Doppler domain or both).


Consider a 64x64 OTSM frame

For UE speed = 0 km/hr;
**delay_taps=[0,0,0,0,0,1,1,2,2]
Doppler_taps=[0,0,0,0,0,0,0,0,0]**
 
You can observe that although there are 9 paths, there are effectively only 3 distinct paths, so the effective diversity as seen by the receiver is 3.

For UE speed= 30 km/hr;
**delay_taps=[0,0,0,0,0,1,1,2,2]
Doppler_taps=[0.35, -0.13, -0.40, 0.46, 0.15, -0.14, -0.12, -0.27]**

Even though the Doppler shifts are slightly different, they are still very close to each other, so the effective diversity is still close to 3.

Now consider UE speed=500 km/hr;
**delay_taps=[0,0,0,0,0,1,1,2,2]
Doppler_taps=[6.10, -7.90, -0.35, -6.46, -6.87, -2.08, 3.94, -7.11, 7.25]**

For very high speed you can see the paths are well separated in the delay-Doppler domain and hence the receiver sees 9 distinct paths leading to improved performance.

For low speed, since the channel does not offer enough Doppler diversity,  you can improve performance by reducing the delay resolution so that the paths are separated along the delay domain. This can be done by increasing M.

Consider a 512x64 frame with UE speed=0 (Note that M=512 and N=64)
delay_taps=[0,0,1,2,3,5,8,13,19];
Doppler_taps=[0,0,0,0,0,0,0,0,0];

You can see that even though the paths are not separated along Doppler, it is separated along delay, so the receiver will still see 9 distinct paths.

The idea is to choose M and N such that the receiver can separate the paths along the delay (by increasing M) and Doppler (by increasing N) domain. Not that M is related to bandwidth and N is related to the time duration of the OTSM frame.

**Comment by l291351760** [comment]
Thank you very much for taking the time to answer my question, your answer made me understand the truth more, thank you very much. I wish you a happy life and good health!
